server:
  port: 1019
  #1。使用cloud-h2（HTTP/2 over TLS）
#  ssl:
#    enabled: true
#    key-store: classpath:server.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: tomcat
  http2:
    enabled: true
  ssl:
    enabled: false

spring:
  application:
    name: cloud-http2-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #1。使用cloud-h2（HTTP/2 over TLS）
#        metadata:
#          secure: true
